// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHVHUCud87K4k3zaMypEmXuszCmSuoWE',
    appId: '1:822039433544:web:98507df097f9f6ad7be37d',
    messagingSenderId: '822039433544',
    projectId: 'fcmexample-58fe4',
    authDomain: 'fcmexample-58fe4.firebaseapp.com',
    storageBucket: 'fcmexample-58fe4.firebasestorage.app',
    measurementId: 'G-Q5J40TCKXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOSSsvtUUEP8d4NrpMLUbXiUid4w6uNU',
    appId: '1:822039433544:android:af9914dda3dc22d57be37d',
    messagingSenderId: '822039433544',
    projectId: 'fcmexample-58fe4',
    storageBucket: 'fcmexample-58fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_dqZcDCP9Y593e7X-P34p7MZ6tUzSfk',
    appId: '1:822039433544:ios:0d4ecb52c0017f907be37d',
    messagingSenderId: '822039433544',
    projectId: 'fcmexample-58fe4',
    storageBucket: 'fcmexample-58fe4.firebasestorage.app',
    iosBundleId: 'com.stec.fcmExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_dqZcDCP9Y593e7X-P34p7MZ6tUzSfk',
    appId: '1:822039433544:ios:40253e7621e87cc77be37d',
    messagingSenderId: '822039433544',
    projectId: 'fcmexample-58fe4',
    storageBucket: 'fcmexample-58fe4.firebasestorage.app',
    iosBundleId: 'com.example.fcmExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuHVHUCud87K4k3zaMypEmXuszCmSuoWE',
    appId: '1:822039433544:web:866fcc7929b91d047be37d',
    messagingSenderId: '822039433544',
    projectId: 'fcmexample-58fe4',
    authDomain: 'fcmexample-58fe4.firebaseapp.com',
    storageBucket: 'fcmexample-58fe4.firebasestorage.app',
    measurementId: 'G-WGHFCTLX3D',
  );
}
